MODULE SIMPLE
IMPLICIT NONE

INTEGER,PARAMETER::NX=600
INTEGER,PARAMETER::NY=300
INTEGER,PARAMETER::NS=1200
INTEGER,PARAMETER::SP=2     !!!POSITION OF IB STRUCTURE y=sp
REAL, PARAMETER::LX=600
REAL, PARAMETER::LY=300

REAL C(0:NX,0:NY),F(0:8,0:NX,0:NY),FEQ(0:8)
REAL DT,DX,DY
REAL X(0:NX),Y(0:NY),U(0:NX,0:NY),V(0:NX,0:NY)
REAL W(0:8),CX(0:8),CY(0:8),OPP(0:8)
REAL CK,CSQ,C0,MSTEP,CS
REAL KC,DS,Q,UMAX,OMEGA,TAU,PI

REAL QXY(0:NX,0:NY),DCDN(0:NX,0:NY)

INTEGER I,J,K,STEP

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
REAL CS_LB(NS),CS_IB(NS),LEVESQUE(NS),LEVESQUE_LB(NX),ERROR1,ERROR

REAL XS(NS),YS(NS)
REAL QS(NS),DCSDN(NS),CIB(NS)
REAL RX,RY,ARC_L
INTEGER X1,X2,Y1,Y2,M,N


END
    